spring:
    datasource:
        url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        generate-ddl: true
    cloud:
        gcp:
            logging:
                enabled: true
            project-id: foody-me
grocery-be:
    external:
        food-details-integrator-be:
            base-url: ${FOOD_DETAILS_BASE_URL}
            details-path: ${grocery-be.external.food-details-integrator-be.base-url}/food/{barcode}
            kcal-consumed-path: ${grocery-be.external.food-details-integrator-be.base-url}/food/{barcode}/kcal?&quantity={quantity}
