spring:
    profiles:
        default: gcp
    datasource:
        url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driverClassName: org.postgresql.Driver
        hikari:
            max-lifetime: 1800000
    jpa:
        defer-datasource-initialization: true
        show-sql: false
        hibernate:
            ddl-auto: update
        generate-ddl: true
    cloud:
        gcp:
            project-id: ${PROJECT_ID}
grocery-be:
    external:
        food-details-integrator-be:
            base-url: ${FOOD_DETAILS_BASE_URL}
            details-path: ${grocery-be.external.food-details-integrator-be.base-url}/food/{barcode}
            kcal-consumed-path: ${grocery-be.external.food-details-integrator-be.base-url}/food/{barcode}/kcal?&quantity={quantity}
