spring:
    datasource:
        url: jdbc:postgresql://${DB_URL}:5432/grocery
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
