apiVersion: apps/v1
kind: Deployment
metadata:
    name: grocery-be-deployment
spec:
    replicas: 2
    template:
        spec:
            containers:
                - name: grocery-be-container
                  resources:
                      limits:
                          memory: "500Mi"
                      requests:
                          memory: "256Mi"
