namespace: grocery
resources:
    - ../../base
commonLabels:
    app: grocery-be
configMapGenerator:
    - name: grocery-be-properties
      literals:
          - DB_URL=192.168.86.5
          - DB_USER=grocerybe
          - FOOD_DETAILS_BASE_URL=http://food-details-integrator-be-service.grocery.svc.cluster.local:8080
secretGenerator:
    - name: grocery-be-secrets
      literals:
          - DB_PASSWORD=Password123
patchesStrategicMerge:
    - deployment_patch.yaml