namespace: grocery
resources:
    - ../../base
commonLabels:
    app: grocery-be
configMapGenerator:
    - name: grocery-be-properties
      literals:
          - spring.datasource.url=jdbc:postgresql://192.168.86.5:5432/grocery
          - spring.datasource.username=grocerybe
secretGenerator:
    - name: grocery-be-secrets
      literals:
          - spring.datasource.password=Password123
patchesStrategicMerge:
    - deployment_patch.yaml