---
name: Build and Push Image to Google Cloud Platform
on:
    push:
        branches: [ feature/springBoot3 ]
jobs:
    build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: grocery-be
            LOCATION: us-central1-docker.pkg.dev
            PROJECT_ID: foody-me
            REPOSITORY: foody-ar
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            -   uses: benjlevesque/short-sha@v1.2
                id: short-sha
                with:
                    length: 7
            - uses: graalvm/setup-graalvm@v1
              with:
                  version: 'latest'
                  java-version: '17'
                  components: 'native-image'
                  github-token: ${{ secrets.GITHUB_TOKEN }}
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    gradle-version: 7.6
            -   uses: google-github-actions/auth@v1
                with:
                    credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            -   uses: google-github-actions/setup-gcloud@v1
                with:
                  project_id: ${{ env.PROJECT_ID }}
            - name: Run build with Gradle Wrapper
              run: ./gradlew bootBuildImage --imageName=$IMAGE_NAME:latest
              env:
                  SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
            - name: Configure Docker Client
              run: |-
                  gcloud auth configure-docker $LOCATION --quiet
            - name: Push Docker Image to Artifact Registry
              run: |-
                  docker tag $IMAGE_NAME:latest $LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
                  docker tag $IMAGE_NAME:latest $LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$SHA
                  docker push $LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
                  docker push $LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$SHA